# Generated by Django 3.0.8 on 2021-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provati', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dept',
            field=models.CharField(choices=[('Admin_depertment', 'Admin_depertment'), ('it_depertment', 'it_depertment'), ('clams_deprtment', 'clams_deprtment'), ('mds_deprtment', 'mds_deprtment'), ('uw_deprtment', 'uw_deprtment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ho_br',
            field=models.CharField(choices=[('ho', 'ho'), ('branch', 'branch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('provatiadmin', 'provatiadmin'), ('provati_itdept', 'provati_itdept'), ('emp', 'emp')], default='provati_itdept', max_length=100),
        ),
    ]
